version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: moodle_mysql_apache_phpfpm
    environment:
      MYSQL_ROOT_PASSWORD: moodleroot
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - moodle_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moodle_apache_phpfpm
    ports:
      - "80:80"
    environment:
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_ADMIN_USER: admin
      MOODLE_ADMIN_PASSWORD: Admin123!
      MOODLE_ADMIN_EMAIL: admin@example.com
      PHP_MAX_INPUT_VARS: 5000
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 600
    volumes:
      - moodle_dir:/var/www/html/moodle
      - moodle_data:/var/www/html/moodledata
      - ./config_moodle/config.php:/var/www/html/moodle/config.php
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moodle_network
      - k6_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'
        reservations:
          cpus: '1'
          memory: '1gb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  k6:
    image: grafana/k6:latest
    user: root
    container_name: moodle_k6_apache_phpfpm
    volumes:
      - ./k6-scripts:/scripts  # Mount folder lokal yang berisi skrip k6
      - ./k6-reports:/reports
    command: run /scripts/test10.js  # Jalankan skrip k6
    # command: run /scripts/test100.js  # Jalankan skrip k6
    # command: run /scripts/test1000.js  # Jalankan skrip k6
    depends_on:
      moodle:
        condition: service_healthy
    networks:
      - k6_network

networks:
  moodle_network:
    driver: bridge
  k6_network:
    driver: bridge

volumes:
  mysql_data:
    external: true  # Gunakan volume yang sudah ada
  moodle_data:
    external: true  # Gunakan volume yang sudah ada
  moodle_dir:
    external: true  # Gunakan volume yang sudah ada